08_django_advance/01_DJANGO_RECAP/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # path('', views.index, name='index'),  # /board/ == board:index
    # read 글 목록(list) render
    # path('articles/', views.list, name='list'),
    # comment 와 구분하기 위해
    path('articles/', views.article_list, name='article_list'),
    # read 글 상세(detail) render
    # path('articles/<int:id>/', views.detail, name='detail'),
    path('articles/<int:article_id>/', views.article_detail, name='article_detail'),

    # create 글쓰기(new) render
    # path('articles/new/', views.new, name='new'),
    path('articles/new/', views.new_article, name='new_article'),
    # create 글 저장(create)
    # path('articles/create/', views.create, name='create'),

    # update 글 수정 쓰기(edit) render
    # path('articles/<int:id>/edit/', views.edit, name='edit'),
    path('articles/<int:article_id>/edit/', views.edit_article, name='edit_article'),

    # update 글 실제 수정(update)
    # path('articles/<int:id>/update/', views.update, name='update'),

    # delete 글 삭제(delete)
    # path('articles/<int:id>/delete/', views.delete, name='delete'),
    path('articles/<int:article_id>/delete/', views.delete_article, name='delete_article'),

    # create comment
    # path('', views.create, name='create'),
    # path('comments/new/', views.new_comment, name='new_comment'),
    # 1:N 종속관계 데이터의 url
    path('articles/<int:article_id>/comments/new/', views.new_comment, name='new_comment'),

    # delete comment
    path('article/<int:article_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment')
]

08_django_advance/01_DJANGO_RECAP/django_recap/urls.py
from django.contrib import admin
from django.urls import path, include  # include 함수로 app url 접근 가능


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('board/', include('board.urls')),
    path('poll/', include('re_poll.urls')),
]

08_django_advance/01_DJANGO_RECAP/home/urls.py
from django.urls import path
from . import views  # views 파일과 연결


# 변수 만들거야!
app_name = 'home'


urlpatterns = [
    # path('', views.index),
    # 이름이 index인 이유는 보통 빈 화면을 index라고 해서 # HOST/home//
    path('', views.index, name='index'),
    # 변수 지정해줬으므로 얘는 뭐라고 해도 home 의 index
    # 다시 html 에서 작업할것임
    # path('hi/<str:name>/', views.hi),  # views 안의 함수를 호출할 수 있게 됨 # HOST/home/hi/
    # variable routing 뭐가 들어오든 변수처리 할 것, views.py 에서 인자 추가
    path('guess/', views.guess, name='guess'),
    path('answer/', views.answer, name='answer'),
]

08_django_advance/01_DJANGO_RECAP/board/models.py
from django.db import models
from django.urls import reverse


class Article(models.Model):
    # id 안넣는 이유, 무조건 생성되게 되어있어서
    title = models.CharField(max_length=100)
    content = models.TextField()
    # 아래는 모두 ORM 에게 확인을 요청하는 과정
    # python manage.py makemigrations board
    # migrations 에서 확인
    # python manage.py sqlmigrate board 0001  > sql 에서 어떤건지 확인
    # python manage.py migrate board 라고 치면 db 에서 생성 및 확인 가능

    # python manage.py shell_plus
    # article = Article()
    # article.title = '안녕'
    # article.content = '안녕안녕'
    # article.save()   == INSERT INTO
    # save가 가능한 이유는 model에 내장되어 있기 때문
    # SELECT * FROM Article == Article.objects.all()
    # SELECT * FROM board.article WHERE id=1
    # == Article.objects.get(id=1)

    # python manage.py shell_plus --print-sql
    # python 코드를 sql 로 번역

    # DELETE FROM board_article WHERE id=1
    # == article = Article.objects.get(id=1) 변수 잡아놓고 삭제
    # article.delete()

    # Article.objects.create(title='hi', content='hihi')
    # 생성

    # python manage.py dbshell > sql 직접 접근

    # article = Article.objects.get(id=2)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    # method 생성
    # DB 에 반영안됨
    # detail 페이지가 있는 경우
    # detail 페이지를 자주 보니까, 절대 주소를 정의해놓고 다른 함수에서 'board:detail' 안써도 되도록
    def get_absolute_url(self):
        return reverse("board:article_detail", kwargs={"article_id": self.id})


class Comment(models.Model):
    # charfield 는 max_length 필수
    # 200 넘어가면 자름
    content = models.CharField(max_length=200)
    # foreignkey 는 integer 는 아니지만, 대충 Article 을 참조해서 id 를 가져오겠다는 의미
    # CASCADE 는 게시글을 삭제했을 때 종속된 것도 지워버림
    # 1:N 관계에서 필수
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # Article 변수를 가져왔기 때문에 class Article 과 순서 바꿀 수 없다.

    # 만들고 다시 migrate

    # c2 = Comment.objects.create(content='엥', article_id=3)
    # Article.objects.get(id=c2.article_id) == c2.article
    #    > comment 에게 article 이 있기 때문에 가능
    # == article.comment_set.all()
    # foreignkey 로 관계 형성!

    # 이제 views.py 의 detail 에 댓글 만들 것

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

08_django_advance/01_DJANGO_RECAP/board/forms.py
from django import forms
from .models import Article, Comment
# Forms.Form => Data 입력 및 검증 + HTML 생성
#            => Model 정보를 모름
# Forms.ModelForm => Data 입력/검증 + HTML 생성, 한겹 더 감싸서 이것저것 기능 추가하기, 그냥 부가적인 것
#                 => Model 정보를 알고있음


# article 이라는 model 에 대한 form
class ArticleModelForm(forms.ModelForm):
    # 1. Data 입력 및 검증
    # 2. HTML 생성
    title = forms.CharField(min_length=2, max_length=100)
    # title = forms.EmailField(min_length=3, required=False)
    # ㄴ 얘는 유효성 검사, valid data, 데이터에 들어갈 수 있는지
    # content = forms.Textarea

    class Meta:
        model = Article
        fields = '__all__'
    # model form 은 model 이 뭔지 지정해주는 것이 매우 중요

"""
# 그냥 form 으로 만드는 예시
class ArticleForm(forms.From):
    title = forms.CharField(min_length=2, max_length=100)
    content = forms.CharField()
    # content 무조건 있어야 함
    # 모든 column 써줘야 함
# 상대적으로 기능이 더 적다
# views 추가로 볼 것
"""


# model 은 그냥 column 만드는 정도,
# form 에서는 데이터의 유효성을 검사하고 HTML form 태그를 핸들링할 수 있음
# meta class > python 에서 개념과 다름
# django 에서 meta 는 일종의 예약어..


class CommentModelForm(forms.ModelForm):
    content = forms.CharField(min_length=2, max_length=200)
    # 200 넘어가면 에러, 저장 안됨 (200을 검증)

    class Meta:
        model = Comment
        # fields = '__all__'
        fields = ('content',)
        # id 는 내 담당 아니야! content 만 볼거임
        # id 검증 X, content 검증

08_django_advance/01_DJANGO_RECAP/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from .models import Article, Comment
from .forms import ArticleModelForm, CommentModelForm
from IPython import embed
# CRUD

"""
# form 예시 (modelform 이랑 다름)
from .forms import ArticleForm
def new_article_with_form(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            # title = form.cleaned_data.get('title')
            # content = form.cleaned_data.get('content')
            # article = Article.objects.create(title=title, content=content)
            article = Article()
            # article.title = request.POST.get('title')  # 검증되지 않은 데이터, 쓰지 마!
            article.title = form.cleaned_data.get('title')  # 검증된 데이터
            article.content = form.cleaned_data.get('content')
            article.save()
            # form 은 article 이라는 model 과 아무 상관 없기 때문에
            # 데이터가 자동으로 들어가지 않아서
            # article 에 관해 다 써줘야 함
            return redirect(article)
    else:
        form = ArticleForm()
    return render(request, 'board/new.html', {
        'form': form,
    })
"""


# 저장은 create, url 은 new 로 하는 것이 보통
@require_http_methods(['GET', 'POST'])
# ㄴ 어차피 get 이랑 post 밖에 없는데 왜? > 사실 더 있음..
# 그래서 이렇게 두 개 다 써야 완성도가 높아짐
def new_article(request):
    What = 'new'
    # 요청 GET/POST 확인
    # 만약 POST 라면
    if request.method == 'POST':
        # ArticleModelForm 의 인스턴스를 생성하고 Data 를 채운다. (binding)
        form = ArticleModelForm(request.POST)
        # shell 을 열어서 시간을 멈춘다..!
        # embed()
        # shell 에서
        # form
        # form.is_valid()
        # form.cleaned_data  > 통과한 데이터
        # form.cleaned_data.get('content')
        # form.as_p()

        # binding 된 form 이 유효한지 체크한다.
        if form.is_valid():
        # 유효하다면, (form을) 저장한다.
            # 여기서 확인하면서 save 하면 아래에서 또 db에 저장되나?
            # embed()
            # save 한 번 하면서 소비돼서 또 저장되지는 않음 (혹은 수정에 가깝게 동작하거나)
            article = form.save()
            # 저장한 article:article_detail 로 redirect
            return redirect(article)  # model 에 get_absolute_url 했기때문에 가능
        # 유효하지 않다면,
        # else:
            # 유효하지 않은 입력데이터를 담은 html 과 에러메시지를 사용자에게 보여준다.
            # return render(request, 'board/new.html', {
            #     'form': form,
                # 유효성 검사 탈락했을 때 데이터랑 에러메시지 받은걸로 변함!
                # 그대로 가져가면 됨
            # })
    # GET 이라면
    else:
        # 비어있는 form(HTML 생성기) 을 만든다.
        form = ArticleModelForm()
        # form 과 html 을 사용자에게 보여준다.
    # 또는 return 하기 직전에 embed 넣고 확인
    # embed()
    return render(request, 'board/form.html', {
        'form': form,
        'What': What,
    })


@require_GET
def article_list(request):
    articles = Article.objects.all()
    return render(request, 'board/list.html', {
        'articles': articles,
    })


@require_GET
def article_detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    # foreignkey 설정하는 순간 article 을 쉽게 불러올 수 있음
    # comments 불러오는 함수 따로 없고 article 에서 다 볼 수 있게
    comments = article.comment_set.all().order_by('-id')  # order ~~ 최근순 정렬
    # == Comment.objects.filter(article_id=article.id)
    comment_form = CommentModelForm()
    return render(request, 'board/detail.html', {
        'article': article,
        #
        'comments': comments,
        'comment_form': comment_form,
    })


@require_http_methods(['GET', 'POST'])
def edit_article(request, article_id):
    What = 'edit'
    article = get_object_or_404(Article, id=article_id)
    if request.method == "POST":
        form = ArticleModelForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect(article)
        # else:
        #     return render(request, 'board/edit.html', {
        #         'form': form,
        #     })
    else:
        # article = get_object_or_404(Article, id=id)
        # data 가 들어가 있는 form
        # 이 때 data 는 앞에서 받은 article
        form = ArticleModelForm(instance=article)
        # return render(request, 'board/edit.html', {
        # 'form': form,
        # })
    return render(request, 'board/form.html', {
        'form': form,
        'What': What,
    })


@require_POST
def delete_article(request, article_id):
    article = get_object_or_404(Aritcle, id=article_id)
    article.delete()
    return redirect('board:article_list')


@require_POST
def new_comment(request, article_id):
    # 1:N 으로 종속된 데이터이기 때문에 연결고리가 필요함
    # /board/comment/new/id/
    # /board/comment/asdf/id/
    # detail page > /board/articles/article_id/comments/comment_id/new,delete, .. > 이게 맞는듯!
    article = get_object_or_404(Article, id=article_id)
    # comment = Comment()
    # comment.content = request.POST.get('comment_content')
    # comment.article_id = article.id
    # 왜 아래처럼 바로 쓰지 않을까?
    # get_object~~ 로 불러오면서 검증과정을 거침
    # comment.article_id = article_id
    # comment.save()

    # comment 도 form 으로 써보기
    # 데이터 받아서 저장해야함
    form = CommentModelForm(request.POST)
    # form.errors
    # embed()
    if form.is_valid():
        # comment = form.save() 라고 안쓰는 이유는,
        # article 은 detail 페이지로 redirect 해야하는데, comment 는 detail 페이지 필요 없음
        # 굳이 변수 하나를 늘릴 필요가 없어짐
        # form.save()
        # save 할 때 NOT NULL constratint failed > board_comment.article_id 가 없기 때문
        comment = form.save(commit=False)
        # save 때 에러 안나기 위해,
        # save 하는 척; 뭐가 저장되긴 함
        # comment = Comment()
        # comment.content = request.POST.get('content')
        # 와 같은 상태라고 할 수 있음
        # 일단 세이브 하는 척 하고 > id 넣어주고 > 진짜 세이브
        comment.article_id = article.id
        comment.save()
        return redirect(article)


@require_POST
def delete_comment(request, article_id, comment_id):
    # article 을 먼저 찾음
    # article = get_object_or_404(Article, id=article_id)
    # article 에서 넘어온 comment_id 를 찾음
    # SELECT * FROM articles WHERE id=article_id
    # comment = get_object_or_404(Comment, id=comment_id)
    # comment 가 article 의 모든 comment 정보 가져온 안에 있다면,
    # SELECT * FROM comments WHERE id=comment_id

    comment = get_object_or_404(Comment, id=comment_id, article_id=article_id)
    # 안전함 + 시간복잡도 다 챙길 수 있는 방법

    # if comment in article.comment_set.all():
        # comment 를 지우고
    comment.delete()
    # 해당 article 페이지로 다시 이동
    return redirect(article)
    """
    comment = get_objects_or_404(Comment, id=comment_id)
    comment.delete()
    > db 에서 삭제
    return redirect(comment.article)
    > 메모리에 아직 남아 있음
    db 에서 삭제되는 시점과 메모리에서 휘발되는 시점이 다름 
    """

08_django_advance/01_DJANGO_RECAP/board/templates/board/_comments.html
<form action="{% url 'board:new_comment' article.id %}" method="POST">
    {% csrf_token %}
        {% comment %} <input type="text" name="comment_content"> {% endcomment %}
        {{ comment_form.as_p }}
        <input type="submit">
    </form>

    {% if comments %}
        <ul>
            {% for comment in comments %}
                <li>
                    {{ comment.content }}
                    {% comment %}
                        id 순서 맞춰서 써야 함
                        안맞추려면 article_id=article.id comment_id=comment.id 이렇게 딱 뭐라고 말해주기
                    {% endcomment %}
                    <form method="POST" action="{% url 'board:delete_comment' article.id comment.id %}">
                        {% csrf_token %}
                        <input type="submit" value="삭제">
                    </form>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

08_django_advance/01_DJANGO_RECAP/board/templates/board/_form.html
{% comment %} <form method="POST">
<!-- form 에 action 이 있다면 new/edit 에서 문제가 생길 것 -->
    {% csrf_token %}
    <div>
        <label for="title">제목:</label>
        <input id="title" name="title" value={{ article.title }}>
    </div>
    <div>
        <label for="content">내용:</label>
        <textarea id="content" name="content" cols="30" rows="10">{{ article.content }}</textarea>
    </div>
    <div>
        <input type="submit" value="제출">
    </div>
</form> {% endcomment %}


<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    {% comment %} {{ form.as_table}} {% endcomment %}
    <!-- form 태그 안에 button 넣으면 자동으로 submit 으로 작동함 -->
    <button>hi</button>
    <input type="submit">    
</form>

08_django_advance/01_DJANGO_RECAP/board/templates/board/detail.html
{% extends 'base.html' %}

{% block title %}Article detail{% endblock %}

{% block body %}
    <h1>{{ article.title }}</h1>
    <div><small>created: {{ article.created_at }}</small><small>updated: {{ article.updated_at }}</small></div>
    <p>
        {{ article.content }}
    </p>
    <div>
        {% comment %} <a href="/board/articles/{{ article.id }}/edit"> {% endcomment %}
        <a href="{% url 'board:edit_article' article.id %}">
            <button>수정</button>
        </a>
    </div>
    <div>
        {% comment %} <a href="{% url 'board:delete' article.id %}">
            <button>삭제</button>
        </a> {% endcomment %}
        <form action="{% url 'board:delete_article' article.id %}" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="삭제" onclick="return confirm('삭제하시겠습니까?')"> {% endcomment %}
            <input id="delButton" type="submit" value="삭제">
        </form>
        {% comment %} <a id="postReq">aa</a> {% endcomment %}
    </div>

    <hr>
    {% include 'board/_comments.html' %}


    <!-- <script>
        const delButton = document.querySelector('#delButton');
        {% comment %} function popUp () {
            return confirm('삭제하시겠습니까?');
        } {% endcomment %}
        function writeHi () {
            document.write('Hi');
        }
        delButton.addEventListener('mouse', popUp);
    </script> -->
{% endblock %}

08_django_advance/01_DJANGO_RECAP/board/templates/board/edit.html
{% extends 'base.html' %}

{% block title %}Edit article{% endblock title %}

{% block body %}
<h1>Edit article</h1>
{% comment %} 왜 중요해요? > db에 반영 될 정보니까! {% endcomment %}
{% comment %} <form action="{% url 'board:update' article.id %}" method="POST"> 
{% comment %} _form.html 로 가져갈 것임
 <form method="POST">
    {% csrf_token %}
    <div>
        <label for="title">제목:</label>
        <input id="title" name="title" value={{ article.title }}>
    </div>
    <div>
        <label for="content">내용:</label>
        <textarea id="content" name="content" cols="30" rows="10">{{ article.content }}</textarea>
    </div>
    <div>
        <input type="submit" value="제출">
    </div>
</form> {% endcomment %}
{% include 'board/_form.html' %}
{% endblock body %}

08_django_advance/01_DJANGO_RECAP/board/templates/board/form.html
{% extends 'base.html' %}

{% block title %}{{ What }} article{% endblock title %}

{% block body %}
<h1>{{ What }} article</h1>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        {% comment %} {{ form.as_table}} {% endcomment %}
        <input type="submit">    
    </form>
{% endblock body %}

08_django_advance/01_DJANGO_RECAP/board/templates/board/index.html
{% extends 'base.html' %}

{% block title %}
    This is Index
{% endblock title %}

{% block body %}
    <h1>Index</h1>
{% endblock body %}

08_django_advance/01_DJANGO_RECAP/board/templates/board/list.html
{% extends 'base.html' %}

{% block title %}Article list{% endblock %}

{% block body %}
    <h1>This is Article list</h1>
    <a href="{% url 'board:new_article' %}">글쓰기</a>
    {% if articles %}
    <!-- 게시글이 있으면, -->
        <ul>
            <!-- articles 는 모든 게시글 객체인데, 글이 하나도 없다면 어떻게 될까? > 위의 if 문으로 연결 -->
            {% for article in articles %}
                <li>
                    <a href="{{ article.get_absolute_url }}">
                        {{ article.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

08_django_advance/01_DJANGO_RECAP/board/templates/board/new.html
{% extends 'base.html' %}

{% block title %}New article{% endblock title %}

{% block body %}
<h1>New article</h1>
{% comment %} <form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.as_table}}
    <input type="submit">    
</form>
{% endcomment %}
{% include 'board/_form.html' %}
{% endblock body %}


{% comment %} 왜 중요해요? > db에 반영 될 정보니까! {% endcomment %}
{% comment %} <form action="{% url 'board:new' %}" method="POST"> {% endcomment %}
<!-- action 이 없으면 제자리 -->
{% comment %} <form method="POST">
    {% csrf_token %}
    <div>
        <label for="title">제목:</label>
        <input id="title" name="title">
    </div>
    <div>
        <label for="content">내용:</label>
        <textarea id="content" name="content" cols="30" rows="10"></textarea>
    </div>
    <div>
        <input type="submit" value="제출">
    </div>
</form> {% endcomment %}
{% comment %} {% include 'board/_form.html' %} {% endcomment %}