08_django_advance/02_MY_RECAP/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('article/', views.article_list, name='article_list'),
]

08_django_advance/02_MY_RECAP/classroom/urls.py
from django.urls import path
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.index, name='index'),
    path('students/', views.list, name='list'),
    path('students/<int:id>/', views.detail, name='detail'),

    path('students/new/', views.new, name='new'),
    path('students/create/', views.create, name='create'),

    path('students/<int:id>/edit', views.edit, name='edit'),
    path('students/<int:id>/update/', views.update, name='update'),

    path('students/<int:id>/delete/', views.delete, name='delete'),
]

08_django_advance/02_MY_RECAP/my_recap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls')),
    path('board/', include('board.urls')),
]

08_django_advance/02_MY_RECAP/board/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse("board:article_detail", kwargs={"article_id": self.pk})
    

08_django_advance/02_MY_RECAP/classroom/models.py
from django.db import models


class Student(models.Model):
    name = models.CharField(max_length=10)
    age = models.IntegerField()
    major = models.TextField()

08_django_advance/02_MY_RECAP/board/forms.py
from django import forms
from .models import Article


class ArticleModelForm(forms.ModelForm):
    title = forms.CharField(min_length=1, max_length=50)

    class Meta:
        model = Article
        fields = '__all__'

08_django_advance/02_MY_RECAP/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_http_methods, require_POST


@require_GET
def article_list(request):
    articles = Article.objects.all()
    return render(request, 'board/article_list.html', {
        'aritcles': articles,
    })

08_django_advance/02_MY_RECAP/classroom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST
from .models import Student


@require_GET
def index(request):
    return render(request, 'classroom/index.html')


@require_GET
def list(request):
    students = Student.objects.all()
    return render(request, 'classroom/list.html', {
        'students': students,
    })


@require_GET
def detail(request, id):
    student = get_object_or_404(Student, id=id)
    return render(request, 'classroom/detail.html', {
        'student': student,
    })


@require_GET
def new(request):
    return render(request, 'classroom/new.html')



@require_POST
def create(request):
    student = Student()
    student.name = request.POST.get('name')
    student.age = request.POST.get('age')
    student.major = request.POST.get('major')
    student.save()
    return redirect('classroom:detail', student.id)


@require_GET
def edit(request, id):
    student = get_object_or_404(Student, id=id)
    return render(request, 'classroom/edit.html', {
        'student': student,
    })


@require_POST
def update(request, id):
    student = get_object_or_404(Student, id=id)
    student.name = request.POST.get('name')
    student.age = request.POST.get('age')
    student.major = request.POST.get('major')
    student.save()
    return redirect('classroom:detail', student.id)


def delete(request, id):
    student = get_object_or_404(Student, id=id)
    student.delete()
    return redirect('classroom:list')

08_django_advance/02_MY_RECAP/classroom/templates/classroom/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block body %}
    {% endblock body %}
</body>
</html>

08_django_advance/02_MY_RECAP/classroom/templates/classroom/detail.html
{% extends 'classroom/base.html' %}

{% block title %}Student detail{% endblock title %}

{% block body %}
    <a href="{% url 'classroom:list' %}">목록으로</a>
    <ul>
        <li>{{ student.name }}</li>
        <li>{{ student.age }}</li>
        <li>{{ student.major }}</li>
    </ul>
    <div>
        <a href="{% url 'classroom:edit' student.id %}">
            <button>수정</button>
        </a>
        <a href="{% url 'classroom:delete' student.id %}">
            <button>삭제</button>
        </a>
    </div>
{% endblock body %}

08_django_advance/02_MY_RECAP/classroom/templates/classroom/edit.html
{% extends 'classroom/base.html' %}

{% block title %}Edit{% endblock title %}

{% block body %}
    <h1>수정하기</h1>
    <form action="{% url 'classroom:update' student.id %}" method="POST">
    {% csrf_token %}
       <div>
            <label for="name">이름</label>
            <input type="text" name="name" id="name" value={{ student.name }}>
        </div>
        <div>
            <label for="age">나이</label>
            <input type="int" name="age" id="age" value={{ student.age }}>
        </div>
        <div>
            <label for="major">전공</label>
            <input type="text" name="major" id="major" value={{ student.major }}>
        </div>
        <div>
            <input type="submit" value="제출">
        </div> 
    </form>
{% endblock body %}

08_django_advance/02_MY_RECAP/classroom/templates/classroom/index.html
{% extends 'classroom/base.html' %}

{% block title %}S2S3{% endblock title %}

{% block body %}
    <h1>S2S3</h1>
    <h2>Hi!</h2>
{% endblock body %}

08_django_advance/02_MY_RECAP/classroom/templates/classroom/list.html
{% extends 'classroom/base.html' %}

{% block title %}Students list{% endblock title %}

{% block body %}
    <h1>S2S3 Student list</h1>
    <a href="{% url 'classroom:new' %}"><button>추가하기</button></a>

    <ul>
        {% for student in students  %}
            <li>
                <a href="{% url 'classroom:detail' student.id %}">
                    {{ student.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock body %}

08_django_advance/02_MY_RECAP/classroom/templates/classroom/new.html
{% extends 'classroom/base.html' %}

{% block title %}작성하기{% endblock title %}


{% block body %}
    <form action="{% url 'classroom:create' %}" method="POST">
    {% csrf_token %}
        <div>
            <label for="name">이름</label>
            <input type="text" name="name" id="name">
        </div>
        <div>
            <label for="age">나이</label>
            <input type="int" name="age" id="age">
        </div>
        <div>
            <label for="major">전공</label>
            <input type="text" name="major" id="major">
        </div>
        <div>
            <input type="submit" value="등록">
        </div>
    </form>
{% endblock body %}

08_django_advance/02_MY_RECAP/my_recap/templates/base.html
<!DOCTYPE html>
<html lan="en">