08_django_advance/04_INSTAGRAM/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('userpage/<int:user_id>/', views.user_page, name='user_page'),
    path('follow/<int:user_id>/', views.follow, name='follow'),
]

08_django_advance/04_INSTAGRAM/instagram/urls.py
from django.contrib import admin
from django.urls import path, include

# static, media DIR 가져오기
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('insta/', include('postings.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

08_django_advance/04_INSTAGRAM/postings/urls.py
from django.urls import path
from . import views

app_name = 'postings'


# insta/
urlpatterns = [
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('create/', views.create_posting, name='create_posting'),
    path('<int:posting_id>/update/', views.update_posting, name='update_posting'),
    path('<int:posting_id>/delete/', views.delete_posting, name='delete_posting'),
    path('<int:posting_id>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:posting_id>/like/', views.toggle_like, name='like')

]

08_django_advance/04_INSTAGRAM/templates/_navbar.html
<nav class="mb-3 navbar sticky-top navbar-expand-lg navbar-light bg-light px-5">
    <a class="navbar-brand" href="{% url 'postings:posting_list' %}">
        <i class="fab fa-instagram"></i> | Instagram
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'postings:create_posting' %}">New</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">MyPage</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{% url 'accounts:signup' %}" class="nav-link">Signup</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

08_django_advance/04_INSTAGRAM/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Fake Insta</title>
    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/9c5b8f215b.js" crossorigin="anonymous"></script>
</head>
<body>
    {% include '_navbar.html' %}
    <div class="container">
    {% block body %}
    {% endblock body %}
    </div>
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
</body>
</html>