08_django_advance/04_INSTAGRAM/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('userpage/<int:user_id>/', views.user_page, name='user_page'),
    path('follow/<int:user_id>/', views.follow, name='follow'),
]

08_django_advance/04_INSTAGRAM/instagram/urls.py
from django.contrib import admin
from django.urls import path, include

# static, media DIR 가져오기
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('insta/', include('postings.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

08_django_advance/04_INSTAGRAM/accounts/models.py
from django.db import models
from django.urls import reverse
# User < AbstractUser < AbstractBaseUser / User 나 AbstratctUser 나 별 차이 없어서...
from django.contrib.auth.models import AbstractUser  # ctrl + 눌러서 model 확인해보기
from django.conf import settings
from faker import Faker
f = Faker()

class User(AbstractUser):  # 위에서 import 한 AbstractUser 상속
    fans = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='stars')  #, blank=True)
    # (User, related~~) 쓰고 migrate 해보면 User 못찾음
    # 'accounts.User' 혹은 self == settings.AUTH_USER_MODEL  # 변수처리 > settings 가서 바꾸면 끝


    def __str__(self):
        return self.username

    @classmethod
    def dummy(cls, n):
        for i in range(n):
            u = cls()
            u.username = f.first_name()
            u.set_password('123qwe')
            u.save()
    # python manage.py shell_plus
    # User.dummy(n)  # 더미 데이터 만들기

    # 팔로우 추가해보기
    # star = User.objects.first()
    # fan1 = User.objects.last()
    # fan2 = User.objects.get(id=2)
    # star.fans.all()  # star 의 fans 보기
    # star.fans.add(fan1)  # star 의 fans 추가
    # star.fans.add(fan2)
    # star.stars.all()  # star 의 stars 확인
    # fan1.stars.all()  # fan1 의 stars 확인
    # fan2.start.all()

    # 내가 나를 팔로우 하는 것 막기

    def get_absolute_url(self):
        return reverse("accounts:user_page", kwargs={"user_id": self.pk})
    

08_django_advance/04_INSTAGRAM/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm  # 가입 / 정보수정 / 로그인

# from .models import User
from django.contrib.auth import get_user_model  # 하나만 바꿔도 되는 코드!!
User = get_user_model()


class CustomUserCreationsForm(UserCreationForm):  # usercreationsform 상속받아서

    class Meta: # (UserCreationForm):
        model = User
        fields = ('username', 'email',)



class CustomAuthenticationForm(AuthenticationForm):
    class Meta:  # 뭔가 저장하는게 아닌 form
        model = User

08_django_advance/04_INSTAGRAM/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib.auth import login as auth_login, logout as auth_logout
# 회원가입용 Form, 인증(login)용 Form
from .forms import CustomAuthenticationForm, CustomUserCreationsForm

# 현재 project 에서 사용할 User 모델을 return 하는 함수
# from .models import User
from django.contrib.auth import get_user_model  # 변수랑 유사하지만 더 안전한 방법, AUTH_USER_MODEL 자체를 가져옴
# shell_plus 에서 get_user_model() 해보면 accounts.models.User 꺼내오는 것을 확인할 수 있다
# get_user_model()() 는 비어있는 User (쓰기 좋은 코드는 아님)
User = get_user_model()


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        form = CustomUserCreationsForm(request.POST)
        if form.is_valid():
            user = form.save()  # 회원가입
            auth_login(request, user)  # 끝나고 로그인
            return redirect('/')
    else:
        form = CustomUserCreationsForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('/')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'accounts/login.html', {
        'form': form,
    })


def logout(request):
    auth_logout(request)
    return redirect('/')


@require_GET
def user_page(request, user_id):
    user_info = get_object_or_404(User, id=user_id)
    return render(request, 'accounts/user_page.html', {
        'user_info': user_info,
    })


def follow(request, user_id):
    fan = request.user
    star = get_object_or_404(User, id=user_id)

    if fan != star:
        if star.fans.filter(id=fan.id).exists():
            star.fans.remove(fan)
        else:
            star.fans.add(fan)
    return redirect(star)  # star 가 결국 User 객체이기 때문에, user_page 로 잘 감

08_django_advance/04_INSTAGRAM/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}   <!-- button div 로 만들어줌 (원래 inline block) -->
            <button class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock body %}

08_django_advance/04_INSTAGRAM/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}   <!-- button div 로 만들어줌 (원래 inline block) -->
            <button class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock body %}

08_django_advance/04_INSTAGRAM/accounts/templates/accounts/user_page.html
{% extends 'base.html' %}
{% block body %}
<div class='row my-5 mx-auto'>
    <div class="col-4 d-flex justify-content-center">
        <!-- 프로필이미지가 들어올공간 -->
        <!-- 이미지 없으면 기본이미지 사용 -->
        <img src="https://picsum.photos/100/100" alt="random-image" class="rounded-circle">
    </div>
    <div class="col-5">
        <div class="row">
            <h2>{{user_info.username}}</h2>
            <!-- 팔로우 버튼, 게시물수, 팔로우 수, 자기소개 등이 들어올 공간 -->
            {% if user != user_info %}
                <a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-light mx-3">
                    {% if user_info in user.stars.all %}팔로잉{% else %}팔로우{% endif %}
                </a>
            {% else %}
                <a href="#" class="btn btn-light mx-3">프로필 편집</a>
            {% endif %}
        </div>
        <div class="row d-flex justify-content-between">
            <h4>게시물 {{user_info.postings.count}}</h4>
            <h4>팔로워 {{user_info.fans.count}}</h4>
            <h4>팔로우 {{user_info.stars.count}}</h4>
        </div>
        <div class="row">
            <h4>자기소개</h4>
        </div>
    </div>
</div>
<div class="card-columns">
    {% for posting in user_info.postings.all %}
        {% include 'postings/_posting.html' %}
    {% endfor %}
</div>
{% endblock %}